### ISSUE TITLE
GeneaLabs\LaravelModelCaching\CacheKey::processEnum()

### ISSUE THREAD

**Issue by Musamba24** [mikebronner/laravel-model-caching#432]
I'm facing this issues in a couple of situations like deleting a model: but in both situations the whole function is almost the same.
It's a try/catch with the delete method of a model inside.

```php
try {
            $article->delete();

            return redirect(request()->header('Referer'));
        } catch (Exception $e) {
            return redirect(request()->header('Referer'))
                ->with([
                        'errormsg' => session()->flash('errorMessage', $e),
                    ]);
        }
```

Here is the full stack error: https://flareapp.io/share/VP6AGVam#F71

 - PHP: 8.1
 - Laravel: 9.x

**Comment by bertoost** [comment]
I'm getting the same error, using `Model::findMany($ids);` method

**Comment by bertoost** [comment]
> I'm getting the same error, using `Model::findMany($ids);` method

In my case it was because one of the `$ids` was a NULL value, instead of an expected INT

**Comment by mikebronner** [comment]
This should be fixed now, thanks for your patience!
