### ISSUE TITLE
Laravel 11 upgrade blocked by laravel-pivot-events dependency

### ISSUE THREAD

**Issue by mscott83** [mikebronner/laravel-model-caching#461]
**Describe the bug**
Upgrading to Laravel 11 is not possible, due to conflicting dependencies

**Stack Trace**
Composer output:

  Problem 1
    - genealabs/laravel-model-caching is locked to version 11.0.0 and an update of this package was not requested.
    - Only one of these can be installed: laravel/framework[v11.0.0, ..., v11.0.6], illuminate/support[v10.17.0, ..., v10.48.2]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - genealabs/laravel-pivot-events 10.0.1 requires illuminate/support ^8.0|^9.0|^10.0 -> satisfiable by illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2].
    - laravel/framework v11.0.0 conflicts with mockery/mockery >=1.6.8.
    - genealabs/laravel-model-caching 11.0.0 requires genealabs/laravel-pivot-events ^10.0 -> satisfiable by genealabs/laravel-pivot-events[10.0.1].
    - mockery/mockery is locked to version 1.6.9 and an update of this package was not requested.
    - Root composer.json requires laravel/framework ^11.0 -> satisfiable by laravel/framework[v11.0.0, ..., v11.0.6].

**Environment**
 - PHP: 8.2
 - OS: n/a
 - Laravel: 10 -> 11
 - Model Caching: 11.0

**Additional context**
As above, due to laravel-pivot-events dependency on illuminate/support, Laravel 11 cannot be installed.

**Comment by mikebronner** [comment]
this should now be fixed in release 11.0.1
